algoritmo "95"
// Funcao:
// Autor: Diego Rosas
// Data : 28/04/2021

var
   V1, V2, S: Inteiro
Funcao Somador(A, B: Inteiro): Inteiro
inicio
      Retorne A + B
FimFuncao

inicio
      Escreva("Digite o primeiro valor: ")
      Leia(V1)
      Escreva("Digite o segundo valor: ")
      Leia(V2)
      S <- Somador(V1, V2)
      EscrevaL
      EscrevaL("A soma dos dois valores eh: ", S)

fimalgoritmo
