algoritmo "39"
// Função :  fazer uma contagem decrescente de 10 até 3
// Autor :
// Data : 06/03/2021
// Seção de Declarações 
var
   cont: Inteiro
   
inicio
      EscrevaL("          CONTAGEM           ")
      EscrevaL("-----------------------------")
      cont <- 10
      Enquanto (cont >= 3) faca
          Escreva(cont)
          cont <- cont - 1
      FimEnquanto
          EscrevaL(" Acabou!")


fimalgoritmo
