algoritmo "71"
// Funcao: Um vetor eh preenchido automaticamente com um valor que recebede uma variavel.
// Autor: Diego Rosas
// Data: 09/05/2021
var
   N, i: Inteiro
   vet: vetor[1..8] de Inteiro
   
inicio
      N <- 999
      EscrevaL("-------------------------------------------------")
      Para i <- 1 ate 8 faca
           vet[i] <- N
           Escreva(" |",vet[i])
      FimPara
      EscrevaL
fimalgoritmo
