algoritmo "61"
// Função :   conta de 0 a 30 de 3  em 3 usando o Enquanto
// Autor :
// Data : 24/03/2021
// Seção de Declarações 
var
   C: Inteiro

inicio
      EscrevaL("-----------------------------------------------")
      EscrevaL("             CONTADOR PROGRESSIVO              ")
      EscrevaL("-----------------------------------------------")
      C <- 0
      Enquanto (C <= 30) faca
         Escreva(C," ")

      C <- C + 3
      FimEnquanto
      Escreva(" Acabou!")

fimalgoritmo
