algoritmo "64"
// Função :   Fazer um contador progressivo com a estrutura PARA.
// Autor :
// Data : 25/03/2021
// Seção de Declarações 
var
   C: Inteiro

inicio
      EscrevaL("-----------------------------------------------")
      EscrevaL("             CONTADROR PROGRESSIVO             ")
      EscrevaL("-----------------------------------------------")
      Para C de 0 ate 40 passo(5) faca
           Escreva(C," ")
      FimPara
      EscrevaL(" Acabou!")



fimalgoritmo
