algoritmo "11"
// Função :   Calcula delta da equação do segundo grau
// Autor :
// Data : 21/02/2021
// Seção de Declarações 
var
   A, B, C, delta: Real
inicio
      Escreval("--------------- Calculadora de Delta --------------")
      Escreva("Digite o  valor de A: ")
      Leia(A)
      Escreva("Digite o  valor de B: ")
      Leia(B)
      Escreva("Digite o  valor de C: ")
      Leia(C)
      delta <- (B^2) - (4*A*C)
      Escreva("O valor de Delta sera:",delta)

fimalgoritmo
