algoritmo "20"
// Função : Calcula e diz se um número é par ou ímpar
// Autor :
// Data : 23/02/2021
// Seção de Declarações 
var
   N, par, impar, teste: Inteiro
inicio
      Escreva("Digite um numero: ")
      Leia(N)
      teste <- (N%2)
      se (teste = 0) entao
         Escreva("O numero informado eh par!")
      senao
         Escreva("O numero informado eh impar!")
      fimse



fimalgoritmo
