algoritmo "65"
// Função :  Fazer um contardor decrescente usando a estrutura PARA.
// Autor :
// Data : 25/03/2021
// Seção de Declarações 
var
   C: Inteiro

inicio
      EscrevaL("-------------------------------------------")
      EscrevaL("           CONTADOR DECRESCENTE            ")
      EscrevaL("-------------------------------------------")
      
      Para C <- 100 ate 0 passo -10 faca
           Escreva(C," ")
      FimPara
      EscrevaL(" Acabou!")
fimalgoritmo
