algoritmo "38_PASSO 04 – REPETIÇÕES ENQUANTO"
// Função :   fazer uma contagem de 6 até 11
// Autor :
// Data : 06/03/2021
// Seção de Declarações 
var
   cont: Inteiro

inicio
      EscrevaL("        CONTAGEM        ")
      EscrevaL("------------------------")
      cont <-  6
      Enquanto (cont <= 11 ) faca
            Escreva(cont)
            cont <- cont + 1
      FimEnquanto
            EscrevaL(" Acabou!")


fimalgoritmo
